# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170308_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teachers/%Y/%m', verbose_name='\u8001\u5e08\u5934\u50cf'),
        ),
    ]
