# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170308_2121'),
        ('course', '0002_auto_20170307_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrganization', verbose_name='\u8bfe\u7a0b\u673a\u6784\u540d\u79f0'),
        ),
    ]
